# Generated by Django 4.2.5 on 2024-01-15 13:05

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', app.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('status', models.CharField(choices=[('E', 'введён'), ('A', 'в работе'), ('F', 'завершён'), ('C', 'отменён'), ('D', 'удалён')], default='E', max_length=1, verbose_name='Статус заявки')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('genus_lat', models.CharField(default='Homo', max_length=50, verbose_name='Род лат.')),
                ('genus_rus', models.CharField(max_length=50, null=True, verbose_name='Род рус. (опц.) ')),
                ('species_lat', models.CharField(default='Sapiens', max_length=50, verbose_name='Вид лат.')),
                ('species_rus', models.CharField(max_length=50, null=True, verbose_name='Вид рус. (опц.) ')),
                ('family_lat', models.CharField(max_length=50, null=True, verbose_name='Семейство лат. (опц.) ')),
                ('family_rus', models.CharField(max_length=50, null=True, verbose_name='Семейство рус. (опц.) ')),
                ('start_date', models.DateField(auto_now=True, null=True, verbose_name='Начало заявки')),
                ('fin_date', models.DateField(blank=True, null=True, verbose_name='Завершение заявки')),
                ('image', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заявки')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор заявки')),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('status', models.CharField(choices=[('A', 'действует'), ('D', 'удален')], default='A', max_length=1, verbose_name='Статус')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название места обитания')),
                ('desc', models.CharField(max_length=1000, verbose_name='Описание места обитания')),
                ('env', models.CharField(choices=[('AG', 'наземно-воздушная'), ('W', 'водная'), ('S', 'почвенная')], default='AG', max_length=2, verbose_name='Среда')),
                ('origin', models.CharField(choices=[('B', 'биогенная'), ('A', 'антропогенная')], default='B', max_length=1, verbose_name='Происхождение')),
                ('image', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inhabitant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.habitat')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal')),
            ],
            options={
                'unique_together': {('habitat', 'species')},
            },
        ),
    ]
