# Generated by Django 4.2.5 on 2024-01-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
