# Generated by Django 4.2.5 on 2024-01-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_habitatspecies_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
