# Generated by Django 4.2.5 on 2024-02-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_inhabitant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitat',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='habitat',
            name='env',
            field=models.CharField(choices=[('AG', 'наземно-воздушная'), ('W', 'водная')], default='AG', max_length=2, verbose_name='Среда'),
        ),
    ]
