# Generated by Django 4.2.5 on 2024-02-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_title_habitat_name_alter_habitat_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='desc',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание места обитания'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
