# Generated by Django 4.2.5 on 2024-02-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_animal_image_alter_habitat_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='total_population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Совокупная численность популяции'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Описание места обитания'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
