# Generated by Django 4.2.5 on 2024-02-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_habitat_total_population_alter_habitat_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabitant',
            name='population',
            field=models.IntegerField(blank=True, default=0, verbose_name='Численность популяции'),
        ),
        migrations.AlterField(
            model_name='habitat',
            name='total_population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Совокупная численность популяций'),
        ),
    ]
