# Generated by Django 4.2.5 on 2024-02-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_inhabitant_population_alter_habitat_total_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='family_lat',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='family_rus',
        ),
        migrations.RemoveField(
            model_name='habitat',
            name='env',
        ),
        migrations.RemoveField(
            model_name='habitat',
            name='total_population',
        ),
        migrations.RemoveField(
            model_name='inhabitant',
            name='population',
        ),
        migrations.AddField(
            model_name='animal',
            name='conservation_status',
            field=models.IntegerField(choices=[(0, 'Исчезнувшие'), (1, 'Исчезнувшие в дикой природе'), (2, 'Находящиеся на грани исчезновения'), (3, 'Исчезающие'), (4, 'Уязвимые'), (5, 'Находящиеся в состоянии, близком к угрожаемому'), (6, 'Зависимые от усилий по сохранению'), (7, 'Пониженная уязвимость'), (8, 'Недостаток данных'), (9, 'Неоценённые')], default=9, max_length=1, verbose_name='Охранный статус'),
        ),
    ]
