# Generated by Django 4.2.5 on 2024-02-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_animal_family_lat_remove_animal_family_rus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='conservation_status',
            field=models.IntegerField(choices=[(0, 'Исчезнувшие'), (1, 'Исчезнувшие в дикой природе'), (2, 'Находящиеся на грани исчезновения'), (3, 'Исчезающие'), (4, 'Уязвимые'), (5, 'Находящиеся в состоянии, близком к угрожаемому'), (6, 'Зависимые от усилий по сохранению'), (7, 'Пониженная уязвимость'), (8, 'Недостаток данных'), (9, 'Неоценённые')], default=9, verbose_name='Охранный статус'),
        ),
    ]
