# Generated by Django 4.2.5 on 2024-02-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_animal_conservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Является ли пользователь модератором?'),
        ),
    ]
