# Generated by Django 4.2.5 on 2024-02-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
        migrations.RemoveField(
            model_name='habitat',
            name='image',
        ),
    ]
