# Generated by Django 4.2.5 on 2024-02-27 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_animal_image_remove_habitat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор заявки'),
        ),
    ]
