# Generated by Django 4.2.5 on 2024-02-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_animal_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Начало заявки'),
        ),
    ]
