# Generated by Django 4.2.5 on 2024-02-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_animal_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='form_date',
            field=models.DateField(null=True, verbose_name='Дата формирования'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('E', 'черновик'), ('A', 'в работе'), ('F', 'одобрена'), ('C', 'отклонена'), ('D', 'удалена')], default='E', max_length=1, verbose_name='Статус заявки'),
        ),
    ]
