# Generated by Django 4.2.5 on 2024-03-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_animal_form_date_alter_animal_fin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
