# Generated by Django 4.2.5 on 2024-03-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitat',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
