# Generated by Django 4.2.5 on 2024-03-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_habitat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitat',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
