# Generated by Django 4.2.5 on 2024-03-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_animal_id_alter_animal_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата создания'),
        ),
    ]
