# Generated by Django 4.2.5 on 2024-03-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_animal_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhabitant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
